### ISSUE TITLE
Replace your apply function with the new closure.apply method.

### ISSUE THREAD

**Issue by marcobambini** [parro-it/gravity-func#2]

**Comment by parro-it** [comment]
I was already changing that, but found a bug in Gravity apply method. I m doing some investigation, then I 'll prepare a PR with at least some failing tests. The bug regards the dynamic _args variable.

**Comment by marcobambini** [comment]
Oh yes please do. Thanks!

**Comment by marcobambini** [comment]
Hi @parro-it, any news about the _args issue?

**Comment by parro-it** [comment]
I'm working on it just now :smile:, I'll publish the PR within minutes ...

**Comment by marcobambini** [comment]
Thanks! :-)

**Comment by parro-it** [comment]
Just completed the transition on `gravity-func`. The new `apply` method works like a charm!!
